#! /bin/bash

# If sshd has no config, generate new keys + config
if [ ! -f /etc/ssh/sshd_config ]; then
    # Regenerate ssh key per container
    dpkg-reconfigure openssh-server
fi

# This only runs once, so remove this startup script
rm /start.d/regenerate-ssh
